- name: Variable usage
  hosts:  localhost
  vars: 
    Course: "Ansible"
    Trainer: "Shiva"
    Duration: "120 hrs"
  tasks:
  - name: Printing the var info
    ansible.builtin.debug: 
      msg: "Hi i am learning {{Course}} from {{Trainer}} and its duration is {{Duration}}"