- name: variable declaration
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Shiva sir"
    Student: "Mohan"
    Duration: "3 Months"
  tasks:
  - name: Printing the declared variables
    ansible.builtin.debug:
     msg: "Hi we are learning {{Course}} from {{Trainer}} and my name is {{Student}} and it's duration is {{Duration}}"


  - name: This is overrided variable declaration declared in task level
    vars:
     Course: "Teraform"
     Duration: "1 Week"
    ansible.builtin.debug:
     msg: "Hi we are learning {{Course}} from {{Trainer}} and my name is {{Student}} and it's duration is {{Duration}}"      