- name: Variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your Username
    private: false
  - name: PASSWORD
    prompt: Please enter the Password
    private: true
  tasks:
  - name: Printing the info
    ansible.builtin.debug:
     msg: "Hi Username is : {{USERNAME}} and Password is : {{PASSWORD}}"