- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
     timings: "7:15 AM"
    ansible.builtin.debug:
     msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}. Timings are: {{timings}}" 