- name: conditional practice
  hosts: web
  become: true
  tasks:
  - name: checking for user id
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: printing the user info
    ansible.builtin.debug:
      msg: "User info is : {{USER}}"  

  - name: User add
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
     
  - name: print the info
    ansible.builtin.debug:
      msg: "Hello World"
