- name: conditional practice
  hosts: web
  become: true
  tasks:
  - name: checking for user id
    ansible.builtin.command: id expense
    ignore_errors: true

  - name: print the info
    ansible.builtin.debug:
      msg: "Hello World"
