- name: Print dict items
  hosts: localhost
  vars: 
   my_dict : 
    Course : "DevOps"
    Trainer: "Shiva"
    Duration : "120hrs"
  tasks:
  - name: printing dict before changing to items
    ansible.builtin.debug:
     msg: "Before chainging : {{ my_dict }}"
  - name: printing the dict after changing to items
    ansible.builtin.debug:
     msg: "After changing : {{ my_dict | dict2items }}"   