- name: Default value
  hosts: localhost
  tasks:
  - name: Printing the default value
    ansible.builtin.debug: 
      msg: "Hello {{Course | default('DevOps')}}"

  - name: printing unique values
    vars: 
      numbers = [1,2,3,3,4,4,4,5]
    ansible.builtin.debug:
     msg: "{{numbers | unique }}"

  - name: change the case of text
    vars:
      value = "Mohan"
    ansible.builtin.debug: 
     msg: {{value | upper}}
     msg: {{value | lower}}    