- name: Loop example of installations
  hosts: web
  become: yes
  tasks:
  - name: Installing packages on loop
    ansible.builtin.dnf:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - {name: 'ansible', state: 'latest'}
    - {name: 'nginx', state: 'absent'}
    - {name: 'mysql', state: 'absent'}