- name: Loop example of installations
  hosts: web
  tasks:
  - name: Installing packages on loop
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: latest
    loop:
    - nginx
    - ansible
    - mysql